services:
  - type: web
    name: watchthefall-orchestrator-v3
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portal.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: RENDER
        value: true
      - key: ENV
        value: production
    headers:
      - type: global
        forward:
          - Cf-Access-Jwt-Assertion